import { Comfortaa } from "next/font/google";
import './../style/style.scss';
import Header from "@/components/header/Header";

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ['latin', 'cyrillic'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap'
});

export const metadata = {
  title: "Green Book",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru" className={`${comfortaa.variable} `}>
      <body>
        <Header />

        {children}
      </body>
    </html>
  );
}
